/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagement;

import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JList;
import javax.swing.JPanel;

/**
 *
 * @author cb3ss
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    patient[] patientArr = new patient[10];
    medicine[] meds = new medicine[99];
    doctorsSet[] doc = new doctorsSet[35];
    Component frame = null;

    public NewJFrame() {
        initComponents();
        meds[0] = new medicine(15, 5, "Napa", "");
        meds[1] = new medicine(40, 5, "Antacid", "");
        meds[2] = new medicine(100, 5, "Civit", "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        patientNameBox = new javax.swing.JTextField();
        patientAgeBox = new javax.swing.JTextField();
        patientDiseaseBox = new javax.swing.JTextField();
        patientIDBox = new javax.swing.JTextField();
        patientSetBtn = new javax.swing.JButton();
        patientIDSearchBtn = new javax.swing.JTextField();
        searchPatientBtn = new javax.swing.JButton();
        patientNameFoundBox = new javax.swing.JTextField();
        patientAgeFoundBox = new javax.swing.JTextField();
        patientDiseaseFoundBox = new javax.swing.JTextField();
        docNameBox = new javax.swing.JTextField();
        docSkillBox = new javax.swing.JTextField();
        docSet = new javax.swing.JButton();
        billPatientIDBox = new javax.swing.JTextField();
        billPatient = new javax.swing.JButton();
        checkInventoryBtn = new javax.swing.JButton();
        sellMedsBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        cashShowBtn = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        clrAllTxt = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        sellMedsBox = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        sellAmount = new javax.swing.JTextField();
        medsBuyBox = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        buyMedsAmount = new javax.swing.JTextField();
        buyMedsBtn = new javax.swing.JButton();
        buyPriceBox = new javax.swing.JTextField();
        asdfas = new javax.swing.JLabel();
        showAmountBox = new javax.swing.JLabel();
        numberOfPatient = new javax.swing.JLabel();
        diseaseByTypeLbl = new javax.swing.JLabel();
        medsCountLbl = new javax.swing.JLabel();
        cashShowLbl = new javax.swing.JLabel();
        diseaseSearchBox = new javax.swing.JTextField();
        ShowAllMeds = new javax.swing.JButton();
        EditProfit = new javax.swing.JButton();
        ShowDoctorInfo = new javax.swing.JButton();
        ShowPatients = new javax.swing.JButton();
        docShowWallet = new javax.swing.JButton();

        jLabel15.setText("jLabel15");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 204, 255));

        patientNameBox.setText("patient name");
        patientNameBox.setToolTipText("set patient name");
        patientNameBox.setName("patientName"); // NOI18N

        patientAgeBox.setText("age");
        patientAgeBox.setToolTipText("age");

        patientDiseaseBox.setText("disease");
        patientDiseaseBox.setToolTipText("disease");

        patientIDBox.setText("patientID");
        patientIDBox.setToolTipText("patientID");
        patientIDBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientIDBoxActionPerformed(evt);
            }
        });

        patientSetBtn.setText("Submit");
        patientSetBtn.setToolTipText("Set Method");
        patientSetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientSetBtnActionPerformed(evt);
            }
        });

        patientIDSearchBtn.setText("patient id");
        patientIDSearchBtn.setToolTipText("patietn id for search");
        patientIDSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientIDSearchBtnActionPerformed(evt);
            }
        });

        searchPatientBtn.setText("Search");
        searchPatientBtn.setToolTipText("Find your Patient");
        searchPatientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPatientBtnActionPerformed(evt);
            }
        });

        patientNameFoundBox.setText("search result");
        patientNameFoundBox.setToolTipText("");
        patientNameFoundBox.setName("patientName"); // NOI18N

        patientAgeFoundBox.setText("search result");
        patientAgeFoundBox.setToolTipText("");
        patientAgeFoundBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientAgeFoundBoxActionPerformed(evt);
            }
        });

        patientDiseaseFoundBox.setText("search result");
        patientDiseaseFoundBox.setToolTipText("");
        patientDiseaseFoundBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientDiseaseFoundBoxActionPerformed(evt);
            }
        });

        docNameBox.setToolTipText("doc name");
        docNameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docNameBoxActionPerformed(evt);
            }
        });

        docSkillBox.setToolTipText("expertise");

        docSet.setText("doc set");
        docSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docSetActionPerformed(evt);
            }
        });

        billPatientIDBox.setToolTipText("patient id");

        billPatient.setText("bill patient");
        billPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billPatientActionPerformed(evt);
            }
        });

        checkInventoryBtn.setText("check inventory");
        checkInventoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInventoryBtnActionPerformed(evt);
            }
        });

        sellMedsBtn.setText("sell medicine");
        sellMedsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellMedsBtnActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 153, 51));
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("patient admission");

        jLabel2.setBackground(new java.awt.Color(255, 153, 51));
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Doctors");

        jLabel3.setBackground(new java.awt.Color(255, 153, 51));
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("pharmacy");

        jLabel4.setBackground(new java.awt.Color(255, 153, 51));
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Manager");

        jButton7.setText("number of patient");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        cashShowBtn.setText("total cash");
        cashShowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashShowBtnActionPerformed(evt);
            }
        });

        jButton9.setText("disease by type");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("medicine at stock");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        clrAllTxt.setText("Clear All Text");
        clrAllTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrAllTxtActionPerformed(evt);
            }
        });

        jLabel5.setText("Name");
        jLabel5.setToolTipText("Name");

        jLabel6.setText("Age");

        jLabel7.setText("Disease");

        jLabel8.setText("ID");

        jLabel9.setText("Name");

        jLabel10.setText("Expertise");

        jLabel11.setText("Name");

        jLabel12.setText("Quantity");

        sellAmount.setToolTipText("Meds Quantity");
        sellAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellAmountActionPerformed(evt);
            }
        });

        medsBuyBox.setToolTipText("Medicine name");

        jLabel13.setText("Name");

        jLabel14.setText("Quantity");

        buyMedsBtn.setText("buy medicine");
        buyMedsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyMedsBtnActionPerformed(evt);
            }
        });

        buyPriceBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyPriceBoxActionPerformed(evt);
            }
        });

        asdfas.setText("buy price");

        showAmountBox.setText("Shows stock info");

        numberOfPatient.setText("N/A");

        diseaseByTypeLbl.setText("N/A");
        diseaseByTypeLbl.setToolTipText("");

        medsCountLbl.setText("N/A");

        cashShowLbl.setText("N/A");

        diseaseSearchBox.setToolTipText("type in disease name to search");

        ShowAllMeds.setText("Show All Meds");
        ShowAllMeds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowAllMedsActionPerformed(evt);
            }
        });

        EditProfit.setText("Edit Profit");
        EditProfit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProfitActionPerformed(evt);
            }
        });

        ShowDoctorInfo.setText("Show Doctor Information");
        ShowDoctorInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowDoctorInfoActionPerformed(evt);
            }
        });

        ShowPatients.setText("Show Patients");
        ShowPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPatientsActionPerformed(evt);
            }
        });

        docShowWallet.setText("show wallet");
        docShowWallet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docShowWalletActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clrAllTxt)
                .addGap(18, 18, 18)
                .addComponent(exitBtn)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)))
                    .addComponent(jLabel9)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel10)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(docShowWallet)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(diseaseSearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(EditProfit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ShowAllMeds)
                                        .addComponent(checkInventoryBtn)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(sellMedsBox, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sellAmount))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(sellMedsBtn)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numberOfPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(showAmountBox)
                                    .addComponent(cashShowLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(diseaseByTypeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(medsCountLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(13, 13, 13))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(patientNameBox)
                                        .addComponent(patientAgeBox)
                                        .addComponent(patientDiseaseBox)
                                        .addComponent(patientIDBox, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(patientSetBtn)
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(patientIDSearchBtn)
                                            .addComponent(searchPatientBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(patientNameFoundBox)
                                    .addComponent(patientAgeFoundBox)
                                    .addComponent(patientDiseaseFoundBox, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(docSkillBox, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(docSet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(docNameBox, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(1, 1, 1)
                                .addComponent(ShowPatients)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(billPatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(billPatientIDBox)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(34, 34, 34)
                                .addComponent(ShowDoctorInfo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cashShowBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(buyMedsBtn)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(asdfas)
                                        .addGap(22, 22, 22)
                                        .addComponent(buyPriceBox, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel14)
                                                    .addGap(22, 22, 22)
                                                    .addComponent(buyMedsAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel13)
                                                    .addGap(36, 36, 36)
                                                    .addComponent(medsBuyBox))))))))
                        .addGap(137, 137, 137))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(patientNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel1))
                                        .addGap(7, 7, 7)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(medsBuyBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel11))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel14)
                                            .addComponent(buyMedsAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(patientAgeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(buyPriceBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(asdfas))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(patientNameFoundBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(patientAgeFoundBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(patientDiseaseBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(sellMedsBtn)
                            .addComponent(buyMedsBtn)
                            .addComponent(patientDiseaseFoundBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(sellMedsBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(sellAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientIDBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientIDSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(ShowAllMeds))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(checkInventoryBtn)
                        .addComponent(showAmountBox))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(patientSetBtn)
                            .addComponent(searchPatientBtn))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ShowDoctorInfo)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(docNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(billPatientIDBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(ShowPatients))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(numberOfPatient)
                    .addComponent(docSkillBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(billPatient))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cashShowBtn)
                    .addComponent(cashShowLbl)
                    .addComponent(docSet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(diseaseByTypeLbl)
                    .addComponent(diseaseSearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(docShowWallet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(medsCountLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EditProfit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitBtn)
                    .addComponent(clrAllTxt))
                .addContainerGap())
        );

        patientDiseaseBox.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int patientI = 0;
    private void patientSetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientSetBtnActionPerformed
        // TODO add your handling code here:
        patientArr[patientI] = new patient(patientNameBox.getText(),
                Integer.parseInt(patientAgeBox.getText()),
                patientDiseaseBox.getText(),
                Integer.parseInt(patientIDBox.getText()));
        try {
            for (int i = 0; i < doc.length; i++) {
                if (patientDiseaseBox.getText().equalsIgnoreCase(doc[i].expertise)) {
                    doc[i].newPatient(patientArr[patientI]);
                    patientArr[patientI].docIndex = i;
                    break;
                }
            }
        } catch (NullPointerException e) {
            for (int i = 0; i < doc.length; i++) {
                if (doc[i].expertise.equalsIgnoreCase("medicine")) {
                    doc[i].newPatient(patientArr[patientI]);

                }
            }
        }

        patientArr[patientI].due += 1000;

        patientI++;
        
    }//GEN-LAST:event_patientSetBtnActionPerformed

    private void cashShowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashShowBtnActionPerformed
        // TODO add your handling code here:

        cashShowLbl.setText(String.valueOf(accounts.cash));
    }//GEN-LAST:event_cashShowBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void searchPatientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPatientBtnActionPerformed
        // TODO add your handling code here:
        int srch_id = Integer.parseInt(patientIDSearchBtn.getText());
        System.out.println(patientIDSearchBtn.getText() + "  " + srch_id);
        try {
            for (int i = 0; i < 10; i++) {
                if (patientArr[i].show_id() == srch_id) {
                    patientNameFoundBox.setText(patientArr[i].show_name());
                    patientAgeFoundBox.setText(Integer.toString(patientArr[i].show_age()));
                    patientDiseaseFoundBox.setText(patientArr[i].show_disease());
                    break;
                }
            }
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Patient not found.");
        }

    }//GEN-LAST:event_searchPatientBtnActionPerformed

    private void clrAllTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrAllTxtActionPerformed
        // TODO add your handling code here:
        patientNameBox.setText("");
        patientIDBox.setText("");
        patientDiseaseBox.setText("");
        patientAgeBox.setText("");
        docNameBox.setText("");
        docSkillBox.setText("");
        billPatientIDBox.setText("");
        cashShowLbl.setText("");
        patientIDSearchBtn.setText("");
        patientNameFoundBox.setText("");
        patientAgeFoundBox.setText("");
        patientDiseaseFoundBox.setText("");
        medsBuyBox.setText("");
        buyMedsAmount.setText("");
        buyPriceBox.setText("");
        sellAmount.setText("");
        sellMedsBox.setText("");

    }//GEN-LAST:event_clrAllTxtActionPerformed

    private void patientIDSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientIDSearchBtnActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_patientIDSearchBtnActionPerformed

    private void buyMedsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyMedsBtnActionPerformed
        // TODO add your handling code here:
        int i = 0;
        String name = medsBuyBox.getText();
        try {
            if (name.equals("")) {
                NumberFormatException n = new NumberFormatException();
                throw n;
            }
            while (i < 99) {
                if (meds[i].name.equalsIgnoreCase(name)) {
                    break;
                } else {
                    i++;
                }
            }
            meds[i].buymedicine(Integer.parseInt(buyMedsAmount.getText()));
        } catch (NumberFormatException n) {
            JOptionPane.showMessageDialog(null, "Enter the medicine name!!");
        } catch (NullPointerException e) {
            meds[i] = new medicine(Integer.parseInt(buyPriceBox.getText()), Integer.parseInt(buyMedsAmount.getText()), name, "");
            JOptionPane.showMessageDialog(null, "New Medicine bought");
        }

    }//GEN-LAST:event_buyMedsBtnActionPerformed

    private void sellMedsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellMedsBtnActionPerformed
        // TODO add your handling code here:
        int i = 0;
        String name = sellMedsBox.getText();
        try {
            if (name.equals("")) {
                NumberFormatException n = new NumberFormatException();
                throw n;
            }
            while (i < 99) {
                if (meds[i].name.equalsIgnoreCase(name)) {
                    break;
                } else {
                    i++;
                }
            }
            meds[i].sellmedicine(Integer.parseInt(sellAmount.getText()));
        } catch (NumberFormatException n) {
            JOptionPane.showMessageDialog(null, "Enter new medicine name!!");
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Medicine not found in inventory");
        }
    }//GEN-LAST:event_sellMedsBtnActionPerformed

    private void sellAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sellAmountActionPerformed

    private void checkInventoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInventoryBtnActionPerformed
        // TODO add your handling code here:
        int i = 0;
        String name = sellMedsBox.getText();
        try {
            if (name.equals("")) {
                NumberFormatException n = new NumberFormatException();
                throw n;
            }
            while (i < 99) {
                if (meds[i].name.equalsIgnoreCase(name)) {
                    break;
                } else {
                    i++;
                }
            }
            showAmountBox.setText(String.valueOf(meds[i].CheckInventory()));
        } catch (NumberFormatException n) {
            JOptionPane.showMessageDialog(null, "Enter the medicine name!!");
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Medicine not found in inventory");
        }
    }//GEN-LAST:event_checkInventoryBtnActionPerformed

    private void patientDiseaseFoundBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientDiseaseFoundBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientDiseaseFoundBoxActionPerformed

    private void patientAgeFoundBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientAgeFoundBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientAgeFoundBoxActionPerformed

    private void buyPriceBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyPriceBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buyPriceBoxActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO ad
        numberOfPatient.setText(String.valueOf(patientI));

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        int diseaseCounter = 0;
        int i = 0;
        try {
            while (i < 10) {
                if (diseaseSearchBox.getText().equalsIgnoreCase(patientArr[i].show_disease())) {
                    diseaseCounter++;

                }
                i++;
            }
        } catch (NullPointerException e) {

        } finally {
            diseaseByTypeLbl.setText(String.valueOf(diseaseCounter));
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void ShowAllMedsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowAllMedsActionPerformed
        // TODO add your handling code here:
        String s = "";
        try {
            for (int c = 0; c < meds.length; c++) {
                if (s.equals("")) {
                    s = meds[c].name + "\n";
                } else {
                    s += meds[c].name + "\n";
                }
            }
        } catch (NullPointerException e) {
        }
        JOptionPane.showMessageDialog(null, s);
    }//GEN-LAST:event_ShowAllMedsActionPerformed

    private void EditProfitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProfitActionPerformed
        // TODO add your handling code here:
        String s = String.valueOf(JOptionPane.showInputDialog(null, "Enter new profit percentage"));
        medicine.EditProfit(Double.parseDouble(s));
    }//GEN-LAST:event_EditProfitActionPerformed

    private void docSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docSetActionPerformed
        // TODO add your handling code here:
        String name = docNameBox.getText();
        String skill = docSkillBox.getText();

        int c = 0;
        try {
            while (c < doc.length) {
                if (doc[c].name.equals("")) {
                    NullPointerException e = new NullPointerException();
                    throw e;
                } else {
                    c++;
                }
            }
        } catch (NullPointerException e) {
            doc[c] = new doctorsSet(name, skill, c);
        }

    }//GEN-LAST:event_docSetActionPerformed

    private void billPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billPatientActionPerformed
        // TODO add your handling code here:

        doc[_billPatient(Integer.parseInt(billPatientIDBox.getText()))].wallet += 500;
        JOptionPane.showMessageDialog(frame, "Billed!");

    }//GEN-LAST:event_billPatientActionPerformed

    private void docNameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docNameBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_docNameBoxActionPerformed

    private void patientIDBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientIDBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientIDBoxActionPerformed

    private void ShowDoctorInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowDoctorInfoActionPerformed
        // TODO add your handling code here:
        String[] docNameList = new String[15];
        try {
            for (int c = 0; c < 15; c++) {
                docNameList[c] = doc[c].name;
            }
        } catch (NullPointerException e) {
        } finally {
            JList list = new JList(docNameList);
            JPanel panel = new JPanel();
            panel.add(list);
            JOptionPane.showMessageDialog(null, panel);
        }
    }//GEN-LAST:event_ShowDoctorInfoActionPerformed
    public int _billPatient(int id) {
        int i = 0;
        try {

            while (i < patientArr.length) {

                if (patientArr[i].show_id() == id) {
                    patientArr[i].due += 600;
                    break;
                }
                i++;
            }
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(frame, "Patient not found!");
            return -1;
        }
        return i;
    }
    private void ShowPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPatientsActionPerformed
        // TODO add your handling code here:
        String s = "";
        int c = 0;
        try {
            while (c < doc.length) {
                if (docNameBox.getText().equalsIgnoreCase(doc[c].name)) {
                    s = doc[c].name + " has these patients under him/her: \n" + doc[c].printPatientName(frame);
                    break;
                } else {
                    c++;
                }
            }
        } catch (NullPointerException e) {
            s = "Doctor name not found, please add name";
        }
        JOptionPane.showMessageDialog(null, s);
    }//GEN-LAST:event_ShowPatientsActionPerformed

    private void docShowWalletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docShowWalletActionPerformed
        // TODO add your handling code here:
        try {
            for (int i = 0; i < doc.length; i++) {
                if (doc[i].name.equalsIgnoreCase(docNameBox.getText())) {
                    JOptionPane.showMessageDialog(frame, String.valueOf(doc[i].wallet));
                    break;
                }
            }
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(frame, "Doctor name not found");
        }
    }//GEN-LAST:event_docShowWalletActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
       int i = 0;
       try
        {
            
            while (i < meds.length)
            {
                String s = meds[i].name;
                i++;
            }
        }
        catch (NullPointerException e){
            
        }
        finally{
            medsCountLbl.setText(String.valueOf(i));
        }

    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditProfit;
    private javax.swing.JButton ShowAllMeds;
    private javax.swing.JButton ShowDoctorInfo;
    private javax.swing.JButton ShowPatients;
    private javax.swing.JLabel asdfas;
    private javax.swing.JButton billPatient;
    private javax.swing.JTextField billPatientIDBox;
    private javax.swing.JTextField buyMedsAmount;
    private javax.swing.JButton buyMedsBtn;
    private javax.swing.JTextField buyPriceBox;
    private javax.swing.JButton cashShowBtn;
    private javax.swing.JLabel cashShowLbl;
    private javax.swing.JButton checkInventoryBtn;
    private javax.swing.JButton clrAllTxt;
    private javax.swing.JLabel diseaseByTypeLbl;
    private javax.swing.JTextField diseaseSearchBox;
    private javax.swing.JTextField docNameBox;
    private javax.swing.JButton docSet;
    private javax.swing.JButton docShowWallet;
    private javax.swing.JTextField docSkillBox;
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField medsBuyBox;
    private javax.swing.JLabel medsCountLbl;
    private javax.swing.JLabel numberOfPatient;
    private javax.swing.JTextField patientAgeBox;
    private javax.swing.JTextField patientAgeFoundBox;
    private javax.swing.JTextField patientDiseaseBox;
    private javax.swing.JTextField patientDiseaseFoundBox;
    private javax.swing.JTextField patientIDBox;
    private javax.swing.JTextField patientIDSearchBtn;
    private javax.swing.JTextField patientNameBox;
    private javax.swing.JTextField patientNameFoundBox;
    private javax.swing.JButton patientSetBtn;
    private javax.swing.JButton searchPatientBtn;
    private javax.swing.JTextField sellAmount;
    private javax.swing.JTextField sellMedsBox;
    private javax.swing.JButton sellMedsBtn;
    private javax.swing.JLabel showAmountBox;
    // End of variables declaration//GEN-END:variables
}
